export const JobFieldOptions = [
  'Administration',
  'Airline',
  'Automotive',
  'Business services',
  'Biotech',
  'Childcare',
  'Cleaning',
  'Community',
  'Computer science',
  'Construction',
  'Customer service',
  'Customer success',
  'Disability services',
  'Driving motor vehicles',
  'Finance',
  'Food service',
  'Graphic design',
  'Government',
  'Healthcare',
  'Home improvement',
  'Human Resources/People',
  'Interior design',
  'IT',
  'Landscaping',
  'Legal',
  'Marketing',
  'Manufacturing',
  'Operations',
  'Pharmaceutical',
  'Project management',
  'Psychology',
  'Real estate',
  'Retail',
  'Sales/Business development',
  'Social work',
  'Software development',
  'Teacher/Tutor/Professor',
  'Voiceover',
  'Writer',
  'Other',
];

export const JobTypeOptions = [
  'Full time',
  'Part time',
  'Interim/Fractional',
  'Contract',
  'Temporary',
  'Project/Gig',
];

export const JobLevelOptions = [
  'Student',
  'Intern',
  'Trainee/Apprentice',
  'Entry level',
  '2+ years experience',
  '5+ years experience',
  'Supervisor',
  'Manager',
  'Director',
  'Vice President',
  'Executive',
  'Board of Directors',
  '10+ years experience (non-supervisory)',
  '15+ years experience (non-supervisory)',
  '20+ years experience (non-supervisory)',
];
